[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    MinUnstakeTokensValue = "10000000000000000000" #10eGLD
    UnBondPeriod = 144000
    UnBondPeriodInEpochs = 10
    MinStepValue = "100000000000000000000"
    StakeEnableEpoch = 124
    StakingV2Epoch = 239
    CorrectLastUnjailedEpoch = 1000000
    DoubleKeyProtectionEnableEpoch = 180
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 2169
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = true

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd1ze6pgefwc7mdx0rhje3h50kkgt26ut3gx8ytezndkz8fjcf96gsqsd7ugw"
    EnabledEpoch = 1000000

[GovernanceSystemSCConfig]
    ProposalCost = "5000000000000000000" #5 eGLD
    NumNodes     = 500
    MinQuorum    = 400
    MinPassThreshold = 300
    MinVetoThreshold = 50
    EnabledEpoch = 1000000

[DelegationManagerSystemSCConfig]
    MinCreationDeposit = "1250000000000000000000" #1.25K eGLD
    EnabledEpoch = 239
    MinStakeAmount = "1000000000000000000" #1 eGLD
    ConfigChangeAddress = "erd1qqqqqqqqqqqqqpgq0gq09608js3gje72v0yzc56k6glc852gl94sgtahk2"

[DelegationSystemSCConfig]
    EnabledEpoch   = 239
    MinServiceFee  = 0
    MaxServiceFee  = 10000
